version: "3.8"

services:
  mailbridge:
    image: registry.echonlabs.com/echonlabs/mailbrige/api:1.0.0
    container_name: mailbridge
    restart: always
    ports:
      - "8002:8000"
    env:
      - .env
    networks:
      - shared

  mailbridge-celery:
    image: celery
    container_name: mailbridge-celery-worker
    restart: always
    command: celery -A app.services.celery_worker worker --loglevel=info
    depends_on:
      - redis
    env:
      - .env
    networks:
      - shared

networks:
  shared:
    external: true