version: "3.8"

services:
  fastapi:
    build: .
    container_name: mailbridge
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - redis
    networks:
      - backend

  celery:
    build: .
    container_name: celery-worker
    restart: always
    command: celery -A app.services.celery_worker worker --loglevel=info
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
